IntelPython/sdc

hpat/_distributed.cpp, hpat/distributed.py, hpat/distributed_analysis.py, hpat/distributed_lower.py, hpat/tests/test_basic.py, setup.py
Currently, it assumes the array that is being indexed is a one-dimensional array of ints and appears to work.  Please see if this makes sense.  If it does, then I will extend it to support multi-dimensional arrays.
=>  Support array shuffling with an index array generated with np.random.permutation

hpat/_distributed.cpp
I reviewed the comment I wrote in a rush before I left and found many grammatical mistakes and a nonsensical sentence, which this patch fixes.  While doing that, noticed a flurry of delete[]s at the end of the file and thought you may have missed some.
=> Fix comments and a memory leak.

hpat/pd_series_ext.py, hpat/tests/test_series.py
For complex input arguments, return complex type.
For all other types, return float64.
Added test cases that were previously unsupported due to typecheck errors from numba.
There are precision problems for some other input data, but this is unrelated issue and should be
addressed separately (if at all, I don't know the requirements).
=> report complex128 result type for Series corr and cov methods

hpat/distributed_analysis.py
@ehsantn needed for q26
Note: q26 still not working since HPAT does neither support 'astype' nor passing int-arrays to daal4py.
=> allowing 1D_VAR distributions when calling daal4py

parquet_reader/hpat_parquet_reader.cpp
Pyarrow has recently updated to 0.11.1, which doesn't have BitUtil::BitNotSet.
Which was removed in https://github.com/apache/arrow/pull/2355.
Use !BitUtil::GetBit instead, as suggested in PR above.
=> Support latest version of pyarrow.

hpat/_dict_ext.cpp, hpat/dict_ext.py, hpat/hiframes_aggregate.py
* adding byte_vec_int64 dictionary
* replacing some macros with templates for better maintanability/debugability/readability
* removing left-overs from previous versions
test_hiframes.TestHiFrames.unique and others still failing, don't know why.
Still requires some clean-up in python part of dictionary handling (using generic path only).
supersedes #72
=> adding dict bytes_vec_int64, cleaning up

hpat/compiler.py
We recently detected integration testing failures with the latest Numba
master and the latest released version of HPAT.
Specifically, the following error was raised:
```
======================================================================
FAIL: test_kmeans (hpat.tests.test_ml.TestML)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/circleci/repo/miniconda3/envs/hpat/lib/python3.6/site-packages/hpat/tests/test_ml.py", line 110, in test_kmeans
self.assertEqual(count_array_OneDs(), 4)
AssertionError: 0 != 4
```
A CI build log can be found here:
https://circleci.com/gh/numba/numba-integration-testing/24
Using `git bisect` the following offending commit was detected in the
Numba Git history: …
=> fixing typing for InlineClosureCallPass

.travis.yml, hpat/tests/test_basic.py, hpat/tests/test_dataframe.py, hpat/tests/test_groupby.py, hpat/tests/test_hiframes.py, hpat/tests/test_io.py, hpat/tests/test_join.py, hpat/tests/test_ml.py, hpat/tests/test_rolling.py, hpat/tests/test_series.py, hpat/tests/test_strings.py
I propose so far to skip tests that fall. Thus, it will be possible to work in parallel to correct the tests and, for example, to do implementation of new features.
@fschlimb @Alexander-Makaryev @Vyacheslav-Smirnov what you think about it?
=> Skipped failed tests

README.rst, buildscripts/hpat-conda-recipe/meta.yaml, docs/source/install.rst, setup.py
Use impi-devel and impi_rt conda packages for
Windows instead of Intel(R) MPI.
This will remove requirement to have already
installed MPI for HPAT build on Windows.
=> Move to use Intel IMPI conda package for Windows

hpat/_distributed.cpp, hpat/_distributed.h, hpat/distributed_lower.py
The "i_malloc.h" header file does not exist since PSXE 2019.
The "fix_i_malloc()" function is used as workaround for "fix
for tensorflows MKL support that overwrites Intel mallocs
which causes Intel MPI to crash"
Remove "i_malloc.h" include and all references to fix_i_malloc() function.
=> Remove using i_malloc stale MPI header

hpat/tests/gen_test_data.py, hpat/tests/test_dataframe.py, hpat/tests/test_series.py, hpat/tests/test_strings.py
Some tests were skipped by me, because I did not think that I needed to separately generate data.
Besides I think that unit tests should be run without additional run of the data generation script.
=> [BUG] Fixed problems with generation parquet files

hpat/tests/test_dataframe.py, hpat/tests/test_series.py, hpat/tests/test_strings.py
Now you should be able test as follows:
`python hpat/tests/test_series.py`
Using the previous import it was possible to test only in this way:
`python -m unittest hpat.tests.test_series`
=> [ENH] using path from root folder for 'gen_test_data' file

hpat/tests/test_dataframe.py
Tests on [issue](https://github.com/IntelPython/hpat/issues/132)
=> Add tests create dataframe

README.rst, setup.py
Could not read README.rst on Windows during building HPAT, because could
not decode 2 symbols using encoding cp1251.
=> Fix decoding issue during reading README.rst

hpat/tests/__init__.py, hpat/tests/test_hpat_jit.py
Introduce tests for current numba limitations:
* jitclass with Dict
* Infer class members from init for jitclass
* list.sort(key=...)
* sorted(a, key=...)
* iterate over tuple
* try/except/raise
* defaultdict
=> [Tests] Introduce tests for Numba limitations

README.rst
Build Tools for Visual Studio 2019 is package of tools and it do not define
which build tool will be used.
It is recommended to use build tools from Visual Studio 2015 (MSVC v140 - VS 2015 C++ build tools (v14.00)).
=> Update instructions for building from source on Windows.

tests_perf/tests/algorithms.py
Row # | Benchmark | Result, s | Min, s | Arithmetic Mean, s | Max, s | Standard Deviation, s
-- | -- | -- | -- | -- | -- | --
1 | algorithms.Nlargest.time_nlargest(50000513, interpreted_python) | 1.23969 | 1.19073 | 1.28418 | 1.48635 | 0.09741
2 | algorithms.Nlargest.time_nlargest(50000513, compiled_python) | 0.07153 | 0.07060 | 0.07347 | 0.09008 | 0.00595
3 | algorithms.Nsmallest.time_nsmallest(80000513, interpreted_python) | 1.29811 | 1.28206 | 1.31318 | 1.37734 | 0.03372
4 | algorithms.Nsmallest.time_nsmallest(80000513, compiled_python) | 0.11481 | 0.11163 | 0.13987 | 0.21200 | 0.04237
5 | algorithms.Var.time_var(200000513, interpreted_python) | 1.56226 | 1.40829 | 1.52438 | 1.62742 | 0.08441
6 | algorithms.Var.time_var(200000513, compiled_python) | 0.74962 | 0.71392 | 0.77756 | …
=> add nlargest, nsmallest, var, mean, median

hpat/datatypes/hpat_pandas_series_functions.py, hpat/hiframes/pd_dataframe_ext.py, hpat/hiframes/pd_series_ext.py, hpat/tests/test_dataframe.py, hpat/tests/test_series.py
Implemented Series.sum() via numpy.nansum().
Is it correct solution or should I implement it in another way?
=> Implement Series.sum() in new style

hpat/datatypes/hpat_pandas_series_functions.py, hpat/hiframes/hiframes_typed.py, hpat/hiframes/pd_series_ext.py, hpat/tests/test_series.py
Note: shallow copy for index is not supported yet.
=> Implement Series.copy() in new style

README.rst, buildscripts/hpat-conda-recipe/meta.yaml, buildscripts/parquet-reader-conda-recipe/meta.yaml, parquet_reader/hpat_parquet_reader.cpp
More info: https://gist.github.com/PokhodenkoSA/becf462bfc68791dd35b7e0a2691905b
=> PyArrow porting 0.14.1 -> 0.15.0

buildscripts/hpat-conda-recipe/meta.yaml
This PR eliminates duplication of package versions using Jinja2 templates.
It is answer to https://github.com/IntelPython/hpat/pull/249#discussion_r338120346.
=> Use Jinja2 templates in hpat-conda-recipe

hpat/__init__.py, setup.py
This PR shows how to create Numba extension for Pandas according the [documentation](http://numba.pydata.org/numba-doc/latest/extending/entrypoints.html).
See test `numba_pandas/tests/test_pandas.py`.
_Implicit_ loading of extension is supported in Numba >= 0.46.
Test file also shows how to load extension _explicitly_ for Numba < 0.46.
For HPAT version not ported to Numba 0.46 it is possible to run the test with Numba 0.46:
comment the line `import hpat.compiler` in `hpat/__init__.py`.
This test is not in CI yet.
`_init_extension()` imports only overloads used in the test. It should be extended for all overloads for Pandas.
I think we should consider moving Pandas overloads to `numba_pandas` package.
=> Add numba_pandas extension

CODE_OF_CONDUCT.md
This document has been borrowed from DAAL4PY project. The document is the list of rules that set the stage of behavior in the Intel(R) Scalable Dataframe Compiler project
=> Adding CODE OF CONDUCT document for contributors

hpat/tests/test_series.py
Fixes #256
For new tests for Series you should:
1. use `self.jit(...)` instead of `hpat.jit(...)`
2. Add test name to `hpat.tests.test_series._numba_not_supported_tests` only if it does not support numba.jit
Also, old Series tests should be revised for reasons why they do not support numba.jit. See `_numba_not_supported_tests` list.
=> Add tests with numba.jit for Series

sdc/tests/tests_perf/README.md, sdc/tests/tests_perf/test_perf_series_str.py, sdc/tests/tests_perf/test_perf_unicode.py, sdc/tests/tests_perf/test_perf_utils.py
Minor changes in TestResults.add()
=> Add README.md for performnace tests

sdc/tests/tests_perf/test_perf_series.py
With the following test two observations were made (both require further investigation):
1. Changing NUMBA_NUM_THREADS env variable (TBB and default threading layer) has no impact on the execution times both in new-style and old-style implementations,
2. Old-style implementation is 1.5-2 times faster than the new-style impl.
=> Adding performance test for Series (A+B).sum()

sdc/distributed.py, sdc/hiframes/aggregate.py, sdc/hiframes/dataframe_pass.py, sdc/hiframes/filter.py, sdc/hiframes/hiframes_typed.py, sdc/hiframes/join.py, sdc/hiframes/pd_dataframe_ext.py, sdc/hiframes/pd_series_ext.py, sdc/io/csv_ext.py, sdc/tests/test_basic.py, sdc/tests/test_dataframe.py, sdc/tests/test_ml.py, setup.py
=> Revert "WIP: Port to numba master"

sdc/tests/tests_perf/test_perf_base.py, sdc/tests/tests_perf/test_perf_utils.py
This PR makes it possible to run benchmarking with results aggregation (by LOAD_PREV_RESULTS=1) using CSV instead of Excel.
=> Add CSV support for TestResults

sdc/datatypes/hpat_pandas_series_functions.py, sdc/tests/test_series.py
fixed method cov and unskiped some tests for cov.
=> fix Series.cov

sdc/tests/test_basic.py, sdc/tests/test_hiframes.py
This PR fixes #351. There are some difference between sdc.jit and numba.jit:
1. sdc.jit do not set parallel=True.
=> Skip hanging tests in test_basic

.travis.yml, azure-pipelines.yml, buildscripts/numba-conda-recipe/recipe/meta.yaml, sdc/distributed.py, sdc/hiframes/aggregate.py, sdc/hiframes/dataframe_pass.py, sdc/hiframes/filter.py, sdc/hiframes/hiframes_typed.py, sdc/hiframes/join.py, sdc/hiframes/pd_dataframe_ext.py, sdc/hiframes/pd_series_ext.py, sdc/io/csv_ext.py, sdc/tests/test_basic.py, sdc/tests/test_d4p.py, sdc/tests/test_dataframe.py, sdc/tests/test_date.py, sdc/tests/test_groupby.py, sdc/tests/test_hiframes.py, sdc/tests/test_hpat_jit.py, sdc/tests/test_io.py, sdc/tests/test_join.py, sdc/tests/test_ml.py, sdc/tests/test_rolling.py, sdc/tests/test_series.py, sdc/tests/test_strings.py, sdc/tests/test_utils.py, setup.py
based on numba `ceab10620764d1ff29e0c0e550d1d5975674819b`
=> Merge numba master

sdc/tests/tests_perf/test_perf_utils.py
Not all conversations was resolved for #347. Here are they.
=> Improvements for benchmark results in CSV

sdc/datatypes/hpat_pandas_series_functions.py, sdc/hiframes/pd_series_ext.py, sdc/tests/test_series.py
=> Revert "Impl operator setitem"

buildscripts/test.py
* added 'xlrd' pckg in benchmark tests conda env, that is needed for tests dump in excel
=> added 'xlrd' for benchmark tests conda env

sdc/tests/tests_perf/test_perf_base.py, sdc/tests/tests_perf/test_perf_series_str.py, sdc/tests/tests_perf/test_perf_unicode.py, sdc/tests/tests_perf/test_perf_utils.py
This PR also closes #393.
This PR make TestBase as base class for all performance tests classes. It enables result collection for all classes.
=> Fix benchmark results collecting

sdc/io/csv_ext.py, sdc/tests/tests_perf/gen_csv.py, sdc/tests/tests_perf/test_perf_read_csv.py
This PR makes PyArrow treads count equal to Numba threads count.
I do not know which threading layer is used by PyArrow. it is possible that there is no intersection with Numba layers.
By default PyArrow uses all available cpus for reading.
=> Make PyArrow cpu_count to correspond NUMBA_NUM_THREADS

sdc/datatypes/hpat_pandas_dataframe_functions.py, sdc/datatypes/hpat_pandas_series_functions.py, sdc/datatypes/hpat_pandas_seriesgroupby_functions.py, sdc/datatypes/hpat_pandas_seriesgroupby_types.py, sdc/datatypes/hpat_pandas_stringmethods_functions.py, sdc/utils.py
We will need to add `inline='always'` (and possible other attributes) to all our `@overload_method`s after numba `@overload_method` refactoring merge. Add our own attribute wrapper so it can be made from one place.
=> Add sdc_overload, sdc_overload_method, sdc_overload_attribute decorators

docs/source/_templates/_api_ref.pandas.dataframe_templ.rst, docs/source/_templates/_api_ref.pandas.series_templ.rst, docs/source/apireference.rst, docs/source/buildscripts/__init__.py, docs/source/buildscripts/apiref_generator.py, docs/source/buildscripts/sdc_doc_utils.py, docs/source/buildscripts/sdc_object_utils.py
Tested locally. No Sphinx warnings introduced
=> Added support for DataFrame generation in API Reference

sdc/tests/test_io.py
This PR is part of #354 without check_jitted() function.
This PR splits TestIO to 3 classes for CSV, Parquet and NumPy. Also it enables some tests for sdc.jit and skip some for numba.jit.
=> Enable tests in test_io.py and split TestIO to 3 classes

sdc/tests/test_utils.py
Uncomment this lines to see which skipped tests are passing now.
You will see that skipped tests are now have status `expected failure` but some tests may became `unexpected success`.
You can unskip `unexpected success` tests because they are passing now.
=> Helps to see which skipped tests are passing now

sdc/tests/tests_perf/test_perf_base.py, sdc/tests/tests_perf/test_perf_series_str.py, sdc/tests/tests_perf/test_perf_unicode.py
test_results_class is attribute of TestBase and could be interpreted by Python UnitTest incorrectly.
=> Rename test_results_class to results_class in tests_perf

README.rst, docs/source/conf.py, sdc/datatypes/hpat_pandas_series_functions.py, sdc/datatypes/hpat_pandas_series_rolling_functions.py, sdc/datatypes/hpat_pandas_stringmethods_functions.py
This PR applies Sphinx extension [sphinxcontrib-programoutput](https://sphinxcontrib-programoutput.readthedocs.io/) and give example of modifying docstrings.
Instead of using this:
```python
.. code-block:: console
> python ./series/series_abs.py
```
Now it should be:
```python
.. command-output:: python ./series/series_abs.py
:cwd: ../../../examples
```
Note: For `:cwd:` use the same example folder you use in:
```python
.. literalinclude:: ../../../examples/series/series_abs.py
```
=> Use examples results in documentation

sdc/config.py, sdc/tests/test_series.py, sdc/tests/test_utils.py, sdc/utils.py
Introduce the way to configure default behavior of sdc_overloads:
1. Config parameter `config_use_parallel_overloads` and environment variable `SDC_AUTO_PARALLEL` which config if `parallel` option is enabled or disabled for all sdc overloads. Default is `False`
2. Config parameter `config_inline_overloads` and environment variable `SDC_AUTO_INLINE` which config is `inline` option is enabled for all sdc overloads. Default is `False`
=> Introduce config options which enables parallel/inline for overloads

README.rst
For Linux.
1. Chennel `defaults` is before channel `conda-forge`
2. `pyarrow` depends on `arrow-cpp`, so installing `arrow-cpp` is not required.
3. `boost` is not required.
4. It is better to use `pyarrow` 0.15.1 because it contains latest patches (1 month period from 0.15.0).
5. `gfortran_linux-64` is not required.
=> Fix README.md: minimize conda environment dependencies.

sdc/datatypes/pandas_series_functions/apply.py, sdc/tests/test_series_apply.py, sdc/tests/tests_perf/test_perf_series.py
`args` are not supported still.
This PR makes possible to use func() which converts type. It is implemented using get_call_type().
Also it uses prange to make `apply()` parallel.
=> Use prange in apply

sdc/tests/tests_perf/generator.py, sdc/tests/tests_perf/test_perf_series.py
This PR fixes problem when two functions with different parameters displays as one test case:
Now you could see separated functions with parameters:
=> Add params to benchmark test case name

sdc/tests/tests_perf/test_perf_utils.py
Fix for SAT-2371.
Now it prints results in this way:
=> Fix results output when run skiped perf tests

sdc/datatypes/common_functions.py, sdc/datatypes/hpat_pandas_series_rolling_functions.py, sdc/utils.py
This PR adds decorator `sdc_register_jitable` which wraps `numba.extending.register_jitable` decorator.
`sdc_register_jitable` takes default parameters for `parallel` and `inline` from `SDC_AUTO_PARALLEL` and `SDC_AUTO_INLINE` environment variables.
I am planning to use it in #541 and #535 and other PRs for improving scalability.
=> Add decorator sdc_register_jitable

buildscripts/sdc-conda-recipe/meta.yaml
This PR fixes internal [benchmarking job](https://teamcity-or.intel.com/viewLog.html?buildId=4541756&buildTypeId=Sat_Sdc_Linux_SdcPy37numpy116_Testing_SdcBenchmarks&tab=buildResultsDiv).
=> Replace pandas<1.0.0a0 to pandas=0.25 due to the buildscripts issue.

sdc/tests/tests_perf/test_perf_base.py
This PR make a fix for #568.
#563 moved warming up to `get_times()` but #568 moved it back and created duplication.
=> Remove warming up from TestBase._test_jitted()

sdc/functions/numpy_like.py, sdc/tests/test_sdc_numpy.py, sdc/tests/tests_perf/test_perf_numpy.py
=> Impl isnan/notnan numpy-like

sdc/tests/test_series.py
I have added this test to show that our implementation differs from Pandas with skipna=False. We return -1000 while Pandas returns nan.
Related issue https://github.com/numba/numba/issues/4125 and PR https://github.com/numba/numba/pull/4210
=> Add test for Series([np.nan]).min(skipna=False)

sdc/tests/tests_perf/test_perf_df_rolling.py, sdc/tests/tests_perf/test_perf_series_operators.py
Change usecase names for better matching methods names in reports:
`DF.rolling.*` -> `DataFrame.rolling.*`
`Series.operator_*` -> `Series.operator.*`
=> Fix names for perf test cases

sdc/tests/test_strings.py
If glob(pattern) cannot find files by pattern, it causes core dump
=> Remove test that causes segfault

sdc/tests/__init__.py, sdc/tests/test_prange_utils.py, sdc/utilities/prange_utils.py
See tests. They show how it should work.
=> Add tests for get_chunks and change formula for get_chunks

sdc/datatypes/hpat_pandas_series_functions.py, sdc/functions/numpy_like.py, sdc/tests/test_sdc_numpy.py, sdc/tests/tests_perf/test_perf_numpy.py, sdc/tests/tests_perf/test_perf_series.py
Only `var` is implemented yet.
This PR is based on #610 because used parallel `nanmean`.
`std` autoscaleup because `Series.std` is implemented via `Series.var`. @densmirn thank you :)
=> Scale var/std

sdc/tests/tests_perf/generator.py
This PR shows that it is not necessary to create text function and call exec. It is possible to define function inside function with values captured from context.
=> Create test case without exec

sdc/datatypes/hpat_pandas_series_functions.py, sdc/functions/numpy_like.py, sdc/tests/tests_perf/test_perf_series.py
=> Call astype scalable

sdc/datatypes/hpat_pandas_series_rolling_functions.py, sdc/tests/tests_perf/test_perf_series_rolling.py
Result of current (multi-thread) implementation:
name | nthreads | type | size | median
-- | -- | -- | -- | --
Series.rolling.kurt | 1 | Python | 800000 | 4.329
Series.rolling.kurt | 1 | SDC | 800000 | 0.467
Series.rolling.kurt | 4 | Python | 800000 | 4.360
Series.rolling.kurt | 4 | SDC | 800000 | 0.248
`Python 1 / SDC 1 = 9.27`
`SDC 1 / SDC 4 = 1.883`
Just in case result of previous (non-optimal) implementation:
name | nthreads | type | size | median
-- | -- | -- | -- | --
Series.rolling.kurt | 1 | Python | 800000 | 4.567
Series.rolling.kurt | 1 | SDC | 800000 | 30.099
`Python 1 / SDC 1 = 0.158`
`SDC 1 / OPT_SDC 1 = 64.452`
`SDC 1 / OPT_SDC 4 = 121.367`
=> Optimize series.rolling.kurt()

sdc/datatypes/hpat_pandas_series_rolling_functions.py, sdc/tests/tests_perf/test_perf_series_rolling.py
Result of current (multi-thread) implementation:
name | nthreads | type | size | median
-- | -- | -- | -- | --
Series.rolling.skew | 1 | Python | 800000 | 5.624
Series.rolling.skew | 1 | SDC | 800000 | 0.479
Series.rolling.skew | 4 | Python | 800000 | 4.794
Series.rolling.skew | 4 | SDC | 800000 | 0.265
`Python 1 / SDC 1 = 11.741`
`SDC 1 / SDC 4 = 1.808`
Just in case result of previous (non-optimal) implementation:
name | nthreads | type | size | median
-- | -- | -- | -- | --
Series.rolling.skew | 1 | Python | 800000 | 4.945
Series.rolling.skew | 1 | SDC | 800000 | 32.357
`Python 1 / SDC 1 = 0.153`
`SDC 1 / OPT_SDC 1 = 67.551`
`SDC 1 / OPT_SDC 4 = 122.102`
=> Optimize series.rolling.skew()

sdc/tests/tests_perf/test_perf_base.py
This PR make running perf tests for Python only when threads count is 1 or NUMBA_NUM_THREADS is not set. It is not necessary to run Python tests with 2 or more NUMBA_NUM_THREADS b/c Python code does not scale.
=> Disable perf tests for Python if NUMBA_NUM_THREADS > 1

sdc/datatypes/hpat_pandas_groupby_functions.py, sdc/tests/tests_perf/__init__.py, sdc/tests/tests_perf/test_perf_df_groupby.py
Some perf test results (no scalability observed at all, need to investigate further):
```
[11:49:11]	[Step 3/3] DataFrame.groupby.min            1        Python 200000  0.009272  0.009256  0.009473       NaN       NaN
[11:49:11]	[Step 3/3]                                           SDC    200000  0.133266  0.132519  0.135123  2.788937  0.005203
[11:49:11]	[Step 3/3]                                  2        Python 200000  0.009156  0.009132  0.009373       NaN       NaN
[11:49:11]	[Step 3/3]                                           SDC    200000  0.130509  0.129958  0.130725  2.700916  0.005142
[11:49:11]	[Step 3/3]                                  4        Python 200000  0.009331  0.009276  0.009525       NaN       NaN
[11:49:11]	[Step 3/3]                                           SDC …
```
=> Adding performance tests for DataFrame.groupby

sdc/datatypes/common_functions.py, sdc/datatypes/hpat_pandas_dataframe_functions.py, sdc/datatypes/hpat_pandas_series_functions.py, sdc/functions/numpy_like.py, sdc/tests/test_dataframe.py, sdc/tests/test_series.py
New implementation not slower than python on 1 thread, scales on 4 cores, but doesn't scale any further:
  |   |   |   | median | min | max | compile | boxing
-- | -- | -- | -- | -- | -- | -- | -- | --
name | nthreads | type | size |   |   |   |   |  
Series.getitem_idx_bool_array | 1 | Python | 1E+07 | 0.282 | 0.2362 | 0.2978 | NaN | NaN
  |   | SDC | 1E+07 | 0.2732 | 0.2648 | 0.2805 | 0.4704 | 0.0012
  | 4 | SDC | 1E+07 | 0.1273 | 0.1205 | 0.1304 | 0.4575 | 0.0007
  | 8 | SDC | 1E+07 | 0.1396 | 0.1332 | 0.1614 | 0.483 | 0.0012
  | 16 | SDC | 1E+07 | 0.1292 | 0.123 | 0.1514 | 0.4871 | 0.0011
Series.getitem_idx_bool_series | 1 | Python | 1E+07 | 0.306 | 0.2906 | 0.3822 | NaN | NaN
  |   | SDC | 1E+07 | 0.3292 | 0.3225 | 0.3915 | 0.4856 | 0.0013
  | 4 | SDC | 1E+07 | 0.1028 | 0.0966 | …
=> Scale getitem by Boolean mask (array or Series) for Series and DFs

sdc/datatypes/hpat_pandas_dataframe_functions.py, sdc/datatypes/hpat_pandas_dataframe_rolling_functions.py, sdc/datatypes/hpat_pandas_groupby_functions.py, sdc/hiframes/pd_dataframe_ext.py
* Manually inline `get_dataframe_data` function calls to reduce excessive increfs/decrefs for large dataframes
`get_dataframe_data`  function itself is still here to avoid breaking any ongoing PR
=> Reduce ir for some functions

docs/source/buildscripts/sdc_object_utils.py, sdc/hiframes/pd_series_ext.py, sdc/rewrites/dataframe_constructor.py
Note:
1. Removed filter for sdc.hiframes because overload(pd.Series) in it
2. I know only unsupported parameters as limitations.
3. Examples for series are in other functions.
4. See also - no in Pandas docs, so no in SDC docs.
=> Docs for pandas.Series()

docs/source/buildscripts/apiref_generator.py
Chack that text before " : " is correct Python variable name.
Eliminated text like "* dict, e.g. {{'foo' : ".
Before:
After:
=> Fix Pandas->SDC docs formatting.

buildscripts/build_doc.py
Examples in documentation build fails due to lack of scipy package in build environment.
That is why error output is present in current documentation:
pkg_resources.DistributionNotFound: The 'scipy' distribution was not found and is required by the application
=> Add scipy to doc build env to avoid examples failure

docs/source/ext_links.txt, docs/source/getting_started.rst, docs/source/performance.rst
I have found that there are several links to Python but they are not resolved until `ext_links.txt` contains link to it.
Also there are `Python*` and `Numba*` mentions without links.
Also I have found that link is not created if there is no space between `Numba Performance Tips` and `<`.
=> Docs fix for external links 

sdc/datatypes/hpat_pandas_dataframe_functions.py
docstring for `df.getitem` was accidentally dropped. So the docstring was restored.
=> add docstring for DF.getitem

sdc/hiframes/pd_series_ext.py
I think "by Intel Scalable DataFrame Compiler" is redundant in doc strings
=> Fix limitations in Series constructor

sdc/hiframes/pd_dataframe_ext.py
Due to this warning we have this in docs:
=> Fix warning about using nopython=True with ngit

setup.py
This PR disables building `parquet_cpp` module. Tests are already disabled.
Parquet support is not work because HPAT pipeline is not work.
=> Disable build of sdc.parquet_cpp

README.rst, buildscripts/build_doc.py, buildscripts/run_benchmarks.py, buildscripts/run_examples.py, buildscripts/sdc-conda-recipe/meta.yaml, docs/source/conf.py, requirements.txt, setup.py
Remove scipy from setup.py, README.txt, and buildscripts
Execute tests and examples locally - it works.
Documentation build fails - the issue is related to incorrect path which appears somewhere during doc build. Denis will take care of this issue.
=> Remove scipy dependency

sdc/datatypes/common_functions.py, sdc/datatypes/hpat_pandas_dataframe_functions.py, sdc/datatypes/hpat_pandas_series_functions.py, sdc/str_arr_ext.py, sdc/tests/test_series.py, sdc/tests/tests_perf/data_generator.py, sdc/tests/tests_perf/test_perf_df.py
Some performance results (from laptop):
**with fix:**
  |   |   |   | median | min | max | compile | boxing
-- | -- | -- | -- | -- | -- | -- | -- | --
name | nthreads | type | size |   |   |   |   |  
DataFrame.getitem_filter_by_value | 1 | Python | 10000000 | 0.328003 | 0.318 | 0.357003 | NaN | NaN
  |   | SDC | 10000000 | 0.34 | 0.287 | 0.404 | 0.715081 | 1.126521
  | 2 | SDC | 10000000 | 0.205 | 0.194 | 0.243 | 0.666005 | 0.958931
  | 4 | SDC | 10000000 | 0.154 | 0.128 | 0.176 | 0.616491 | 0.935159
**without fix (on master):**
  |   |   |   | median | min | max | compile | boxing
-- | -- | -- | -- | -- | -- | -- | -- | --
name | nthreads | type | size |   |   |   |   |  
DataFrame.getitem_filter_by_value | 1 | Python | 10000000 | 0.314004 | 0.311996 | 0.318 | NaN | NaN
  |   | SDC | …
=> Optimize getitem operations by checking for same indexes

buildscripts/azure/template-linux-macos.yml, buildscripts/azure/template-windows.yml, sdc/datatypes/hpat_pandas_dataframe_functions.py, sdc/hiframes/pd_dataframe_ext.py, sdc/hiframes/pd_dataframe_type.py, sdc/tests/__init__.py, sdc/tests/test_dataframe.py, sdc/tests/test_groupby.py, sdc/tests/test_io.py, sdc/tests/test_rolling.py, sdc/tests/test_utils.py
Extension for [#801](https://github.com/IntelPython/sdc/pull/801)
Implementation of new DataFrame structure based on lists instead of tuples
Improved df.count() codegen for testing
Example:
```
df = pd.DataFrame({'A': [1,2,3], 'B': [.5, .6, .7], 'C': [4, 5, 6], 'D': ['a', 'b', 'c']})
(['A', 'B', 'C', 'D'],)
([array([1, 2, 3], dtype=int64), array([4, 5, 6], dtype=int64)], [array([0.5, 0.6, 0.7])], [array(['a', 'b', 'c'], dtype=object)])
```
Reproduce:
```
@njit
def run_df():
df = pd.DataFrame({'A': [1,2,3], 'B': [.5, .6, .7], 'C': [4, 5, 6], 'D': ['a', 'b', 'c']})
print(df._columns)
print(df._data)
return df.count()
```
=> Redesign DataFrame structure

buildscripts/run_examples.py, buildscripts/utilities.py
It occurs that conda resolver can take Intel SDC package
not from first channel where it is found.
Specify particular SDC version to avoid this in examples
for now.
Also print info for environment creation and package installing
=> Specify sdc version from channel for examples testing

conda-recipe/meta.yaml
When building our distribution, conflicts seem to appear when pin_compatible('numpy') is used. Removing this to get Windows full builds to work.
=> Remove pin_compatible; introduces conflicts when building

sdc/extensions/indexes/range_index_ext.py
It will help with porting to Numba 0.50
=> Fix imports from Numba

sdc/hiframes/api.py, sdc/hiframes/boxing.py, sdc/str_arr_ext.py
This PR solves issues with leaked Series data/indexes allocated in unit tests and not freed later, due to excessive increfs/missed decrefs. Running the same tests that create series from different inputs multiple times, shows that memory grows without fix and the fix resolves this.
=> SAT-2855 - Memory leaks cause segfaults in unit tests

README.rst, docs/source/getting_started.rst
Recently I have an idea that cause of installing SDC 0.32.0 instead of newer 0.33.0/0.33.1 is the order of channels in install command: "-c intel/label/beta -c intel -c defaults -c conda-forge". There was an idea that if move conda-forge in second position then all will be ok.
I have tested this and this is not works.
Looks like the root cause in complex environment modification required to install new 0.33.0 / 0.33.1 packages. I have tried to preinstall pyarrwo and pandas packages with required versions and after that install command works fine.
So, looks like need to change install commands in ReadME to the following:
> conda create -n sdc-env python=<3.7 or 3.6> pyarrow=0.17.0 pandas=0.25.3 -c anaconda -c conda-forge
> conda activate sdc-env
> conda install sdc -c intel/label/beta -c …
=> Update sdc install commands to install latest version

buildscripts/azure/template-linux-macos.yml, buildscripts/azure/template-windows.yml
Motivation: on Windows Azure jobs are cancelled since they cannot pass
in 2h time. As a temp solution increase timeouts until parallel test
execution is added.
=> Increasing CI timeouts

sdc/extensions/indexes/range_index_ext.py, sdc/tests/test_indexes.py
Pandas 1.0 supports int32 types in RangeIndex but SDC not:
- Remove int32 from invalid types
- Change Exception type and message
=> Fix RangeIndex tests

sdc/datatypes/hpat_pandas_functions.py, sdc/hiframes/pd_dataframe_ext.py, sdc/hiframes/pd_dataframe_type.py, sdc/io/csv_ext.py, sdc/str_arr_type.py, sdc/tests/test_io.py
Motivation: returning Tuple of columns read from csv file with
pyarrow csv reader from objmode and further calling init_dataframe
ctor to create native DF turned out to be inefficient in sense of
LLVM IR size and compilation time. With this PR we now rely on DF
unboxing and return py DF from objmode.
**Compile time of read_csv + df.count():**
solutions\columns | 4 | 8 | 16 | 32 | 64 | 128 | 256
-- | -- | -- | -- | -- | -- | -- | --
Numba master + both SDC fixes   (2b8b0034d74) | 8.897234 | 9.306839 | 10.54691 | 12.52175 | 17.41399 | 30.47878 | 65.63396
Numba master + SDC fix #1 (964e498a9) | 9.283413 | 9.83861 | 13.30219 | 21.7165 | 53.07618 | 187.4615 | 1026.31
Numba 0.50.1  + SDC master | 9.212505 | 10.238 | 14.08183 | 25.16768 | 72.9872 | 290.3359 | 2141.832
Ratio (both fixes to …
=> Changing csv_reader_py impl to return df from objmode

sdc/datatypes/hpat_pandas_functions.py, sdc/hiframes/pd_dataframe_ext.py, sdc/hiframes/pd_dataframe_type.py, sdc/io/csv_ext.py, sdc/str_arr_type.py, sdc/tests/test_io.py
Reverts IntelPython/sdc#918
Due to unstable tests on Windows
=> Revert "Changing csv_reader_py impl to return df from objmode"

sdc/decorators.py, sdc/tests/__init__.py, sdc/tests/test_compile_time.py, sdc/utilities/utils.py
This adds a decorator to print Numba compilation stats for a decorated function
and all nested functions (literally all compiled overloads). Filtering
can be made using decorator arguments.
NOTE: this may show a bit lesser times than compile time calculated using
common approach via first_run_exec_time - second_run_exec_time.
=> Adding debug decorator to print Numba compile stats

examples/dataframe/dataframe_columns.py, sdc/datatypes/hpat_pandas_dataframe_functions.py, sdc/datatypes/hpat_pandas_groupby_functions.py, sdc/hiframes/boxing.py, sdc/hiframes/pd_dataframe_ext.py, sdc/hiframes/pd_dataframe_type.py, sdc/tests/test_dataframe.py
Motivation: before this change column names were passed to DF ctor as
arguments of LiteralString types (each name of it's own type), which
seems to add to linear dependency of LLVM IR size and hence impact
DF ctor compile time. Since this information is saved into DF type
itself and can be captured in any of DF methods on typing it's proposed
to remove columns from DF model struct as redundant.
=> Remove column names from DataFrame model

sdc/datatypes/hpat_pandas_dataframe_functions.py, sdc/hiframes/api.py, sdc/hiframes/pd_dataframe_ext.py, sdc/hiframes/pd_series_ext.py, sdc/rewrites/dataframe_constructor.py, sdc/tests/test_dataframe.py
Motivation: init_dataframe was implemented via Numba intrinsic taking *args,
which seems to generate redundant extractvalue/insertvalue LLVM
instructions, producing quadratic IR when number of DF columns grows and affecting
total compilation time of function that create large DFs. This PR
replaces singe init_dataframe with multiple functions basing on number of columns
in a DF which are generated at compile time, thus avoiding use of *args.
n_columns |   | 8 | 16 | 32 | 64 | 128 | 256 | 512
-- | -- | -- | -- | -- | -- | -- | -- | --
LLVM IR size, Mb | on master | 0.287622 | 0.55394 | 1.262865 | 3.383549 | 10.44003 | 35.79943 | 131.384
LLVM IR size, Mb | With PR #936 | 0.143275 | 0.209119 | 0.341938 | 0.608992 | 1.143528 | 2.220672 | 4.406426
ratio without/with |   | 2.007482 | 2.648924 | …
=> Implements init_dataframe as multiple codegen functions

sdc/datatypes/hpat_pandas_dataframe_functions.py, sdc/hiframes/pd_dataframe_ext.py
Motivation: df[idx] when idx is a slice produces DataFrame with the same
internal structure as original one (only index type may change). Hence
it can be copied and filled with column[idx] slices, which improves
compilation time.
=> Refactor df.geitem by slice idx to improve compile time

sdc/_str_ext.cpp, sdc/datatypes/common_functions.py, sdc/datatypes/hpat_pandas_series_functions.py, sdc/functions/numpy_like.py, sdc/functions/sort.py, sdc/native/module.cpp, sdc/native/sort.cpp, sdc/native/stable_sort.cpp, sdc/native/utils.cpp, sdc/native/utils.hpp, sdc/str_arr_ext.py, sdc/tests/test_sdc_numpy.py, sdc/tests/test_series.py
Motivation: for StringArray type legacy implementation of stable sort
computed result when sorting with ascending=False by reversing the
result of argsorting with ascending=True, which produces wrong order in
groups of elements with the same value. Implemented solution adds
new function argument 'ascening' and uses it when calling native function
impl via serial stable_sort.
=> Fixing bug in stability of mergesort impl for StringArray

sdc/datatypes/categorical/functions.py, sdc/datatypes/series/boxing.py, sdc/tests/categorical/test_df_category.py, sdc/tests/categorical/test_series_category.py, sdc/tests/indexes/test_int64_index.py, sdc/tests/test_series_ops.py, sdc/utilities/sdc_typing_utils.py
=> Fixes pack of failed tests

conda-recipe/meta.yaml, requirements.txt, sdc/datatypes/hpat_pandas_series_functions.py, sdc/functions/numpy_like.py, setup.py
Motivation: keep up with latest Numba release.
Note: commit 2017e6c28d is actually just a workaround for numba=0.53.1 regressions and probably should be reverted once referred issues are fixed.
=> Moving to numba=0.53.1

sdc/__init__.py, sdc/extensions/sdc_hashmap_ext.py, sdc/extensions/sdc_hashmap_type.py, sdc/native/conc_dict_module.cpp, sdc/native/hashmap.hpp, sdc/tests/__init__.py, sdc/tests/test_tbb_hashmap.py, setup.py
Motivation: SDC relies on typed.Dict implementation in many core
pandas algorithms, and it doesn't support concurrent read/writes.
To fill this gap we add ConcurrentDict type which will be used if
threading layer is TBB.
=> Initial version of ConcurrentDict container via TBB hashmap

conda-recipe/meta.yaml
This PR is to follow Anaconda BKM to build using the oldest numpy with a stable API, which is 1.16. Intel's oldest numpy supporting python 3.7 is numpy 1.17, so we use that only at build time so ensure broadest compatibility with newer numpy versions.
Relates to https://github.com/tensorflow/tensorflow/issues/47691  (TensorFlow does not support numpy 1.20.x)
=> Dependency for numpy 1.17

README.rst, conda-recipe/meta.yaml, docs/source/getting_started.rst, requirements.txt, sdc/io/csv_ext.py, setup.py
Motivation: keep up with the latest versions of dependencies
=> Migrating to pyarrow=4.0.1

README.rst, azure-pipelines.yml, conda-recipe/meta.yaml, requirements.txt, sdc/_str_ext.cpp, sdc/tests/test_io.py, setup.py
Motivation: include numba fixes from 0.54.1 and unblock internal CI
=> Migrating numba from 0.54.0 to 0.54.1

sdc/__init__.py, sdc/functions/tuple_utils.py, sdc/rewrites/dict_zip_tuples.py, sdc/tests/test_basic.py, sdc/tests/test_utils.py
Motivation: there's no easy way to create Numba LiteralStrKeyDict
objects for const dicts with many elements. This adds a special overload
for dict builtin that creates LiteralStrKeyDict from tuple of pairs
('col_name', col_data).
=> Adds zip and dict builtins overloads to support easy literal dict ctor

README.rst, conda-recipe/meta.yaml, docs/source/getting_started.rst, requirements.txt, sdc/datatypes/categorical/boxing.py, sdc/datatypes/hpat_pandas_functions.py, sdc/datatypes/hpat_pandas_series_rolling_functions.py, sdc/io/csv_ext.py, sdc/tests/categorical/__init__.py, sdc/tests/categorical/test_categorical.py, sdc/tests/categorical/test_df_category.py, sdc/tests/categorical/test_series_category.py, sdc/tests/test_groupby.py, setup.py
Motivation: keep up to date with latest versions of dependencies.
=> Migrating to pandas=1.3.4

sdc/rewrites/read_csv_consts.py, sdc/tests/test_io.py
Motivation: fixes a bug in RewriteReadCsv rewrite that fails compilation
when exception is raised during the match phase because variable
defining value of read_csv parameter is not ir.Expr node but ir.Global
(and thus has no op attribute).
=> Allow global values to be used in read_csv params (names, usecols)
