IntelPython/sdc

hpat/_str_ext.cpp
hpat/str_arr_ext.py

@unbox Pandas.Series -> StringArray

---

hpat/_quantile_alg.cpp

This can be simplified further, but this is good enough for now.

Remove duplicate code and simplify.

---

docs/source/install.rst

Updating windows build instructions.

updating windows build instructions

---

hpat/hiframes_typed.py
hpat/pd_series_ext.py
hpat/pd_timestamp_ext.py
hpat/tests/test_date.py

Initial support for year, month, day, etc. attributes of DatetimeIndex.

---

examples/d4p_linreg.py
hpat/ml/d4p.py
hpat/tests/test_d4p.py

* Needed to convert to lower level API for typing and lowering
* Adding box/unbox for result and model objects
* Adding test (logistic regression)

D4p boxing unboxing

---

hpat/hiframes_typed.py
hpat/pd_series_ext.py
hpat/tests/test_series.py

Implementation is based on series.apply.

support series.combine

---

hpat/_str_decode.cpp

@ehsantn @shssf @Alexander-Makaryev

Compatibility with python<3.7

---

examples/accel_example.py
examples/d4p_kmeans.py
examples/d4p_linreg.py
examples/hiframes_concat.py
examples/hiframes_cumsum.py
examples/hiframes_filter.py
examples/hiframes_merge.py
examples/hiframes_pivot.py
examples/hiframes_rolling.py
examples/hiframes_shift.py
examples/hiframes_sort.py
examples/intraday_mean.py
examples/intraday_mean_rand.py
examples/k-means.py
examples/kernel_density_estimation.py
examples/kernel_density_estimation_pq.py
examples/kernel_density_estimation_pq_hdfs.py
examples/linear_regression.py
examples/logistic_regression.py
examples/logistic_regression_rand.py
examples/ml_mnb.py
examples/ml_svc.py
examples/pi.py
examples/ros_example1.py
setup.py
tutorial/intraday_mean.py

The result produced by `python setup.py style -a` command only.
Exceptions:
- in `setup.py` very long line converted to list manually
- `[df['BUY'] == True]` automatically converted into `[df['BUY']]`. Not sure in it.

Code style change part 1

---

setup.cfg

Forgot to add config file for `pycodestyle` in PR #103

Style check config fo pystyle

---

hpat/config.py
hpat/decorators.py

Currently controled by `HPAT_CONFIG_PIPELINE_HPAT=1`. Planned to use in testing purposes.

Add Numba decorator use option

---

hpat/hiframes/boxing.py
hpat/tests/test_dataframe.py

fixing unboxing of categoricals in DFs

---

hpat/tests/test_basic.py
hpat/tests/test_dataframe.py
hpat/tests/test_groupby.py
hpat/tests/test_io.py
hpat/tests/test_join.py
hpat/tests/test_ml.py
hpat/tests/test_series.py
hpat/tests/test_strings.py

This is Work In Progress PR. Just to test my changes in CI.

Fixing tests

---

docs/rename_function.py
docs/usersource/GettingStarted.rst
examples/Basic_DataFrame.py
examples/series_basic.py

Added two basic examples with series and dataframe operations

[WIP]adding few examples to getting started section

---

hpat/datatypes/hpat_pandas_series_functions.py

Moved the code from other PR to separate one.

Prototype type validator for typing stage

---

hpat/_cv.cpp
hpat/_daal.cpp
hpat/_datetime_ext.cpp
hpat/_datetime_ext.h
hpat/_dict_ext.cpp
hpat/_distributed.cpp
hpat/_distributed.h
hpat/_hiframes.cpp
hpat/_hpat_common.h
hpat/_hpat_sort.h
hpat/_import_py.h
hpat/_meminfo.h
hpat/_ros.cpp
hpat/_set_ext.cpp
hpat/_str_decode.cpp
hpat/_str_ext.cpp
hpat/io/_csv.cpp
hpat/io/_csv.h
hpat/io/_hdf5.cpp
hpat/io/_io.cpp
hpat/io/_parquet.cpp
hpat/io/_xe_wrapper.cpp
hpat/stringlib/asciilib.h
hpat/stringlib/bytesobject.cpp
hpat/stringlib/codecs.h
hpat/stringlib/ucs1lib.h
hpat/stringlib/ucs2lib.h
hpat/stringlib/ucs4lib.h
hpat/stringlib/undef.h
parquet_reader/hpat_parquet_reader.cpp

Copyright header automatically added to all `cpp` and `h` files

Code name rename part 3

---

hpat/__init__.py
hpat/config.py
hpat/datatypes/hpat_pandas_dataframe_pass.py

Origin
```
Ran 95 tests in 16.922s
FAILED (failures=3, errors=59, skipped=14)
```
This PR
```
Ran 95 tests in 47.460s
FAILED (errors=25, skipped=14)
```
I will address an issue with median() in separate PR #294

Pandas.DataFrame class support part 3

---

docs/source/apireference.rst
docs/source/compilation.rst
docs/source/conf.py
docs/source/info.py
docs/source/module_info.py
docs/source/other_intel_python_projects.rst
docs/source/sdc_info.py

* Got rid of autodoc/autosummary/autolabel
* Slightly revised sections of the SDC documentation, mainly to get rid of autodoc/autosummary
* Implemented scripts to traverse module classes and parse docstrings

[WIP] Documentation development

---

sdc/tests/tests_perf/__init__.py
sdc/tests/tests_perf/gen_csv.py
sdc/tests/tests_perf/test_perf_read_csv.py
sdc/tests/tests_perf/test_perf_utils.py

This PR slightly improve utility functions and implement benchmark in common way.

Benchmark for read_csv() via PyArrow

---

sdc/distributed.py
sdc/hiframes/aggregate.py
sdc/hiframes/dataframe_pass.py
sdc/hiframes/filter.py
sdc/hiframes/hiframes_typed.py
sdc/hiframes/join.py
sdc/hiframes/pd_dataframe_ext.py
sdc/hiframes/pd_series_ext.py
sdc/io/csv_ext.py
sdc/tests/test_basic.py
sdc/tests/test_dataframe.py
sdc/tests/test_ml.py
setup.py

**Please, do not merge until we decide merging startegy**
The only broken part part for now is `df.apply` and `df.groupby` with lambdas due to lambda handling changes in master
Adapt to numba master changes:
* `get_parfor_reductions` interface changes
* `define` interface changes
* Parfor dead code regression fix (https://github.com/numba/numba/pull/4724) is not yet merged into master, mark tests as expected failures 
* `series.map` fixes due to lamda handling changes
* removed outdated `boost_regex` dependency

WIP: Port to numba master

---

sdc/tests/test_dataframe.py
sdc/tests/test_series.py

Unskip tests which pass in numba.jit.

---

sdc/tests/tests_perf/test_perf_utils.py

Fix error when perf test results created without drivers.

---

sdc/datatypes/hpat_pandas_series_functions.py

Assumed that it was accidentally modified with new docs.

Revert unnecessary code modifications

---

sdc/hiframes/hiframes_untyped.py
sdc/io/csv_ext.py
sdc/tests/gen_test_data.py
sdc/tests/test_hpat_jit.py
sdc/tests/test_io.py

Support for empty strings in read_csv()

---

buildscripts/test.py
sdc/datatypes/hpat_pandas_functions.py
sdc/hiframes/hiframes_untyped.py
sdc/io/csv_ext.py
sdc/tests/test_io.py

Implement pandas.read_csv() in numba.jit

---

.travis.yml
azure-pipelines.yml
buildscripts/build.py
buildscripts/test.py

Pin Python=3.7.3 for Python=3.7

---

buildscripts/autogen_sources.py
sdc/datatypes/common_functions.py
sdc/datatypes/hpat_pandas_dataframe_functions.py
sdc/datatypes/hpat_pandas_series_autogenerated.py
sdc/datatypes/hpat_pandas_series_functions.py
sdc/datatypes/hpat_pandas_stringmethods_functions.py
sdc/datatypes/hpat_pandas_stringmethods_types.py
sdc/datatypes/sdc_function_templates.py
sdc/tests/test_series.py

@Hardcode84 @kozlov-alexey please review ASAP

Replace overload* with sdc_overload*

---

sdc/tests/tests_perf/test_perf_series.py

Close #487 
Close #488 
Close #490 
Close #492 
Close #493 
Close #496

add perf tests

---

sdc/tests/tests_perf/test_perf_df.py

append, count, drop, max, mean, median, min, pct_change, prod, std, sum, var

Add gen df test perf

---

README.rst

Rearranged REFERENCES section to the end. Removed MPI example.

Updated README.rst - References & MPI

---

sdc/tests/tests_perf/test_perf_base.py
sdc/tests/tests_perf/test_perf_df.py
sdc/tests/tests_perf/test_perf_series.py
sdc/tests/tests_perf/test_perf_series_operators.py
sdc/tests/tests_perf/test_perf_series_str.py
sdc/tests/tests_perf/test_perf_utils.py

Collect benchmark results from all suites

---

sdc/datatypes/hpat_pandas_series_functions.py
sdc/tests/tests_perf/test_perf_series.py

Scale Series.count()

---

sdc/datatypes/hpat_pandas_series_functions.py

Series isna/notna numpy-like call

---

sdc/datatypes/hpat_pandas_series_functions.py
sdc/functions/numpy_like.py
sdc/tests/test_sdc_numpy.py
sdc/tests/test_series.py
sdc/tests/tests_perf/test_perf_numpy.py
sdc/tests/tests_perf/test_perf_series.py

Scale Series.cumsum()

---

README.rst
buildscripts/numba-conda-recipe/recipe/meta.yaml

latest commit in release0.48 branch

switch to numba 0.48 

---

sdc/datatypes/hpat_pandas_functions.py
sdc/hiframes/hiframes_untyped.py
sdc/tests/gen_test_data.py
sdc/tests/test_io.py

This PR implements read_csv(sep, delimiter) and eliminates code duplication in tests for read_csv.

Read csv delimiter

---

sdc/hiframes/boxing.py
sdc/hiframes/pd_dataframe_ext.py
sdc/hiframes/pd_dataframe_type.py
sdc/tests/test_dataframe.py

* Remove lazy unboxing
* Simplify and force inline `get_dataframe_data` function to remove excessive increfs/decrefs
Based on #663

Optimize get_dataframe_data function

---

buildscripts/azure/template-linux-macos.yml
buildscripts/azure/template-windows.yml
buildscripts/run_examples.py
buildscripts/utilities.py

- Separate script
- Use packages from Intel Anaconda channel
- Remove useless logic - examples should always be passed.

Update examples execution

---

sdc/datatypes/hpat_pandas_dataframe_functions.py
sdc/tests/test_dataframe.py
sdc/utilities/sdc_typing_utils.py

Covered case when setting exising column to DF.

Implement private df method _set_column which sets existing column to the df

---

sdc/tests/tests_perf/test_perf_df.py

Add perf test for DF.isna

---

sdc/datatypes/hpat_pandas_series_functions.py
sdc/functions/numpy_like.py

Series.astype improved
Series.operator.gt good as before

Add numpy.astype_no_inline

---

sdc/datatypes/pandas_series_functions/map.py

Docs for Series.map()

---

sdc/datatypes/hpat_pandas_series_functions.py

Docs for Series.prod()

---

sdc/datatypes/pandas_series_functions/apply.py

Docs Series.apply()

---

docs/source/_templates/_api_ref.pandas.io_templ.rst
docs/source/apireference.rst
docs/source/buildscripts/apiref_generator.py
sdc/datatypes/hpat_pandas_functions.py

Docs for pandas.read_csv()

---

sdc/datatypes/hpat_pandas_series_functions.py

Docs series copy

---

sdc/datatypes/hpat_pandas_series_functions.py

Docs for Series.sum()

---

sdc/datatypes/hpat_pandas_series_functions.py

Docs for Series.mean()

---

sdc/datatypes/hpat_pandas_dataframe_functions.py
sdc/datatypes/hpat_pandas_groupby_functions.py

With this PR total exec time of groping operation of groupby is reduced x3 times, also threaded parallelism is added via separation of work of filling groupby dict among threads (scales poorly though):

Initial attempt to parallelize groupby

---

README.rst
docs/source/conf.py
docs/source/getting_started.rst

- Add conda/wheel install instructions to README.rst and getting_started.rst
- Update build instruction in README.rst
- Add link from getting_started to build instructions in README.rst
- Update copyright in doc config
- Add step of scipy installation for doc build in README.rst

Add conda/whee linstall steps; update build instructions

---

docs/source/buildscripts/examples_generator.py
docs/source/conf.py
docs/source/examples.rst
sdc/datatypes/hpat_pandas_stringmethods_functions.py

Required to insert generated examples `examples_list.rst` to `examples.rst`.

Add generating of examples list

---

sdc/datatypes/hpat_pandas_dataframe_functions.py
sdc/datatypes/hpat_pandas_dataframe_rolling_functions.py
sdc/datatypes/hpat_pandas_series_functions.py
sdc/datatypes/hpat_pandas_series_rolling_functions.py
sdc/datatypes/hpat_pandas_stringmethods_functions.py

I made restrictions for all methods except string methods ljust and lower, @densmirn  where can I provide documentation for them?

Add perf limitation

---

docs/source/getting_started.rst

I see that most of the topics required in TODO for this section is moved to section Getting Performance With Intel® SDC. So here I have created links to this section and provide other usefull links to API Reference and Numba docs.

Add Getting Started: What If I Get Poor Performance?

---

buildscripts/run_examples.py
docs/source/getting_started.rst
examples/basic_usage_nyse_predict.py

Add example to Basic Usage in doc

---

docs/source/getting_started.rst

Add Getting Started: Measuring Performance

---

sdc/datatypes/hpat_pandas_series_functions.py

correct doc for Series.ne, Series.add, Series.sub, Series.mul, Series.div, Series.truediv, Series.floordiv, Series.pow, Series.mod, Series.eq, Series.ge, Series.lt, Series.gt, Series.le

correct doc for Series.lt

---

README.rst

Fix README code format in Running unit tests

---

buildscripts/sdc-conda-recipe/run_test.bat
buildscripts/sdc-conda-recipe/run_test.sh

I did not find parameter in unittest for excluding tests from run. I know that pytest has exclude parameter. Moving to PyTest is separate task.
So the solution now is rough because it requires to support the list of tests in 2 files. It is just for checking the solution. I will try to find exclude flag for unittest or will try to move to pytest.

Run tests in separate processes

---

README.rst
buildscripts/sdc-conda-recipe/meta.yaml
requirements.txt
setup.py

Also removed mentions of 0.48.0. I hope I have found all places.

Update to Numba 0.49.1

---

README.rst

Add information about tbb to README
Should it be merged to master or integration branch?

Update README with tbb information

---

sdc/tests/gen_test_data.py

Commented parquet usage in test data generation.

SAT-2941 - SDC: Function tests failed for all platforms

---

README.rst
sdc/native/utils.hpp
sdc/transport/hpat_transport_single_process.cpp

Revert "Merge integration/release 0.33.0 to master"

---

README.rst
sdc/extensions/indexes/range_index_ext.py
sdc/native/utils.hpp
sdc/transport/hpat_transport_single_process.cpp

Sorry, for squashing previous PR.

Integration/release 0.33.0

---

README.rst
conda-recipe/meta.yaml
sdc/tests/test_indexes.py
sdc/tests/test_rolling.py
sdc/tests/test_series.py
sdc/tests/test_utils.py
setup.py

Update Pandas 1.0.5

---

conda-recipe/meta.yaml

Checking to see whether macOS CI is failing because of macOS compiler toolchain.

Attempt to get CI to work on macOS

---

sdc/datatypes/hpat_pandas_functions.py
sdc/hiframes/pd_dataframe_ext.py
sdc/hiframes/pd_dataframe_type.py
sdc/io/csv_ext.py
sdc/str_arr_type.py
sdc/tests/test_io.py

This reverts commit 30122b26c25c51464b5fd0c8f39f28300b26761b.

Return back csv_reader_py changes from #918

---

README.rst
conda-recipe/meta.yaml
docs/source/_templates/_api_ref.pandas.window_templ.rst
docs/source/getting_started.rst
requirements.txt
sdc/datatypes/hpat_pandas_series_functions.py
sdc/tests/test_rolling.py
sdc/tests/test_series.py
setup.py

Motivation: use latest versions of dependencies.

Move to pandas=1.2.0

---

README.rst
conda-recipe/meta.yaml
docs/source/getting_started.rst
requirements.txt
setup.py

Updates pyarrow dependency to version 2.0.0

PyArrow version updated to 2.0.0

---

.bandit
README.rst
buildscripts/azure/template-linux-macos.yml
buildscripts/azure/template-windows.yml
buildscripts/build_doc.py
buildscripts/run_examples.py
buildscripts/test.py
buildscripts/test_conda_install.py
buildscripts/utilities.py
sdc/native/sort.cpp
sdc/native/stable_sort.cpp
sdc/native/utils.cpp

Motivation: merge of bugfixes from master to be included in 2021.3.

Merge from master 2021_w22

---

conda-recipe/meta.yaml

Motivation: compatibility with external packages.

add numpy 1.19
